### ISSUE TITLE
Misleading info in Optimize getting started

### ISSUE THREAD

**Issue by dwright-adobe** [adobe/aepsdk-optimize-android#122]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-optimize-android/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

This paragraph appears right before the section on Tracking and how to use offer.displayed(), implying to customers that they don't need to implement offer.displayed() because "A4T works out of the box". Consider rewording to make it clear what additional work is required for A4T to work:
"Once Analytics is listed as the reporting source for an activity on Target UI, A4T works out of the box in the Optimize SDK. The Experience Edge handles forwarding any Target A4T payloads to Adobe Analytics and no additional action is required on the client-side."

https://github.com/adobe/aepsdk-optimize-android/blob/main/Documentation/getting-started.md

### Environment

Android

**Comment by spoorthipujariadobe** [comment]
Fixed by #121
